import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("first")

  return (
    <html lang="ar" dir="rtl">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
